name: 'Setup wasm-tools'
description: 'Set up your GitHub Actions workflow with a specific version of wasm-tools'
author: 'Rajat Jindal<rajatjindal83@gmail.com>'
inputs:
  version:
    required: false
    description: 'version of wasm-tools to setup'
    default: latest
  github_token:
    required: false
    description: 'When downloading wasm-tools, GitHub may rate limit anonymous downloads. Set this to use authenticated downloads, which are are subject to a higher limits.'
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: '../../dist/wasm-tools/setup/index.js'
