name: 'Setup wasmtime'
description: 'Set up your GitHub Actions workflow with a specific version of wasmtime'
author: 'Rajat Jindal<rajatjindal83@gmail.com>'
inputs:
  version:
    required: false
    description: 'version of wasmtime to setup'
    default: latest
  github_token:
    required: false
    description: 'When downloading wasmtime, GitHub may rate limit anonymous downloads. Set this to use authenticated downloads, which are are subject to a higher limits.'
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: '../../dist/wasmtime/setup/index.js'
