name: 'Setup wit-bindgen'
description: 'Set up your GitHub Actions workflow with a specific version of wit-bindgen'
author: 'Rajat Jindal<rajatjindal83@gmail.com>'
inputs:
  version:
    required: false
    description: 'version of wit-bindgen to setup'
    default: latest
  github_token:
    required: false
    description: 'When downloading wit-bindgen, GitHub may rate limit anonymous downloads. Set this to use authenticated downloads, which are are subject to a higher limits.'
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: '../../dist/wit-bindgen/setup/index.js'
