name: Ensure dist package is up to date
on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 19

      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run package
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: ensure dist is up to date
        run: git diff --exit-code
