name: wit-bindgen
on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run package
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: setup-wit-bindgen
          path: dist/wit-bindgen/setup/index.js

  setup-default:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve saved Github action
        uses: actions/download-artifact@v3
        with:
          name: setup-wit-bindgen
          path: dist/wit-bindgen/setup/

      - name: setup wit-bindgen
        uses: ./wit-bindgen/setup/
        with:
          github_token: ${{ github.token }}

      - name: verify wit-bindgen setup
        run: wit-bindgen --version

  setup-version:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ["0.16.0", "0.19.0"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve saved Github action
        uses: actions/download-artifact@v3
        with:
          name: setup-wit-bindgen
          path: dist/wit-bindgen/setup/

      - name: setup wit-bindgen
        uses: ./wit-bindgen/setup/
        with:
          version: ${{ matrix.version }}
          github_token: ${{ github.token }}

      - name: wit-bindgen setup successful
        if: ${{ contains(env.WIT_BINDGEN_VERSION, matrix.version) }}
        run: echo "wit-bindgen setup successful"

      - name: wit-bindgen setup failed
        if: ${{ !contains(env.WIT_BINDGEN_VERSION, matrix.version) }}
        run: |
          echo "expected version: ${{ matrix.version }}, found: ${{ env.WIT_BINDGEN_VERSION }}"
          exit 1

  setup-v-version:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ["0.16.0", "0.19.0"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve saved Github action
        uses: actions/download-artifact@v3
        with:
          name: setup-wit-bindgen
          path: dist/wit-bindgen/setup/

      - name: setup wit-bindgen with v-prefixed version
        uses: ./wit-bindgen/setup/
        with:
          version: v${{ matrix.version }}
          github_token: ${{ github.token }}

      - name: wit-bindgen setup successful
        if: ${{ contains(env.WIT_BINDGEN_VERSION, matrix.version) }}
        run: echo "wit-bindgen setup successful"

      - name: wit-bindgen setup failed
        if: ${{ !contains(env.WIT_BINDGEN_VERSION, matrix.version) }}
        run: |
          echo "expected version: ${{ matrix.version }}, found: ${{ env.WIT_BINDGEN_VERSION }}"
          exit 1
